version: "3.7"

volumes:
  simulador-dat:
    name: "dat.tlaco.tec"
    driver: local

networks: 

  simulador-net:
    name: "net.tlaco.tec"
    driver: bridge
    ipam: 
      driver: default

services:

  simulador-pql:
    container_name: "pql.tlaco.tec"
    image: oobravom/simulador-pql:1.0-SNAPSHOT
    networks: 
      simulador-net:
    volumes:
      - "simulador-dat:/simulador-pql"
  
  simulador-key:
    container_name: "key.tlaco.tec"
    image: oobravom/simulador-key:1.0-Final
    networks: 
      simulador-net:
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - KC_PROXY=edge
      - KC_HTTP_PORT=80
      - KC_HTTPS_PORT=443
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=key.tlaco.tec
      - KC_DB_URL=jdbc:postgresql://pql.tlaco.tec:5432/simulador
    depends_on:
      - simulador-pql
    labels:
      - traefik.enable=true
      - traefik.http.routers.simulador-key.tls=true
      - traefik.http.routers.simulador-key.entrypoints=web,websecure
      - traefik.http.routers.simulador-key.rule=Host(`key.tlaco.tec`)
      - traefik.http.routers.simulador-key.tls.certresolver=simulador-tek-rlr
      
  simulador-mdb:
    container_name: "mdb.tlaco.tec"
    image: oobravom/simulador-mdb:1.0-SNAPSHOT
    networks: 
      simulador-net:
    ports:
      - "3309:3306"

  simulador-api:
    container_name: "api.tlaco.tec"
    image: oobravom/simulador-api:1.0-Final
    networks: 
      simulador-net:
    ports:
      - "6060:80"
      - "6061:443"
    depends_on:
      - simulador-key
      - simulador-mdb
    environment:
      - default.http.port=80
      - default.https.port=443
      - simulador.mdb.password=iz0819
      - simulador.mdb.port.number=3306
      - simulador.mdb.user=simulador-api
      - simulador.mdb.data.base=simulador
      - simulador.mdb.server.name=mdb.tlaco.tec
      - simulador.key.realms.url=https://key.tlaco.tec/realms
    labels:
      - traefik.enable=true
      - traefik.http.routers.simulador-api.tls=true
      - traefik.http.routers.simulador-api.entrypoints=web,websecure
      - traefik.http.routers.simulador-api.rule=Host(`api.tlaco.tec`)
      - traefik.http.routers.simulador-api.tls.certresolver=simulador-tek-rlr
      
  simulador-web:
    container_name: "web.tlaco.tec"
    image: oobravom/simulador-web:1.0-Final
    networks: 
      simulador-net:
    ports:
      - "9090:80"
      - "9091:443"
    depends_on:
      - simulador-api
    environment:
      - default.http.port=80
      - default.https.port=443
      - simulador.key.auth.url=https://key.tlaco.tec
      - simulador.api.rest.url=http://api.tlaco.tec/simulador/rest
    labels:
      - traefik.enable=true
      - traefik.http.routers.simulador-web.tls=true
      - traefik.http.routers.simulador-web.entrypoints=web,websecure
      - traefik.http.routers.simulador-web.rule=Host(`web.tlaco.tec`)
      - traefik.http.routers.simulador-web.tls.certresolver=simulador-tek-rlr
      
  simulador-tek:
    image: traefik:v2.8.1
    container_name: "tek.tlaco.tec"
    networks: 
      simulador-net:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./acme.json:/acme.json
      - ./traefik.log:/traefik.log
      - ./simulador-tek-usr:/simulador-tek-usr
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.dashboard.middlewares=auth
      - traefik.http.routers.api.rule=Host(`tek.tlaco.tec`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.rule=Host(`tek.tlaco.tec`)
      - traefik.http.middlewares.auth.basicauth.usersfile=/simulador-tek-usr
      - traefik.http.routers.simulador-tek.tls.certresolver=simulador-tek-rlr
