api:
  dashboard: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  simulador-tek-rlr:
    acme:
      email: oobravom@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web

log:
  filePath: "/traefik.log"
  level: INFO
  format: json
